name: tictactic
description: TicTacToe - juego multijugador en tiempo real con Firebase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  firebase_core: ^3.13.0
  firebase_auth: ^5.1.4
  firebase_database: ^11.0.4
  cloud_firestore: ^5.1.0

  google_fonts: ^6.2.1
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/icon_app.png
  adaptive_icon_background: "#0F2A44"
  adaptive_icon_foreground: assets/icons/icon_app.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
