// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaIjuK9zmaCRLfxUcxxEcGbQPqvQN6gic',
    appId: '1:935567171465:web:a40bd7bd37bc6abf770b58',
    messagingSenderId: '935567171465',
    projectId: 'tictactoe-74b9e',
    authDomain: 'tictactoe-74b9e.firebaseapp.com',
    databaseURL: 'https://tictactoe-74b9e-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-74b9e.firebasestorage.app',
    measurementId: 'G-HNLVGQLNJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSE1HcctDi9ra7bVhd7-zO0083A5nbtPU',
    appId: '1:935567171465:android:8d8e9fd1d13c58ec770b58',
    messagingSenderId: '935567171465',
    projectId: 'tictactoe-74b9e',
    databaseURL: 'https://tictactoe-74b9e-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-74b9e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaIjuK9zmaCRLfxUcxxEcGbQPqvQN6gic',
    appId: '1:935567171465:web:a6b6e36b91d477c4770b58',
    messagingSenderId: '935567171465',
    projectId: 'tictactoe-74b9e',
    authDomain: 'tictactoe-74b9e.firebaseapp.com',
    databaseURL: 'https://tictactoe-74b9e-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-74b9e.firebasestorage.app',
    measurementId: 'G-YV7ZWTTMM9',
  );
}
